"""Second migration

Revision ID: 3785509ab1b2
Revises: fdf939f4d0db
Create Date: 2021-05-31 15:29:54.218869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3785509ab1b2'
down_revision = 'fdf939f4d0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
